FROM ubuntu:20.04

RUN useradd -ms /bin/bash suyanne
ARG USER=suyanne
ARG DEBIAN_FRONTEND=noninteractive

SHELL ["/bin/bash", "-c"]

RUN apt-get update --fix-missing

RUN apt-get install -y \
    git \
    sudo \
    python3-pip \
    build-essential \
    cmake \
    pkg-config \
    # Optional OpenCV dependencies
    # libjpeg-dev \
    # libtiff5-dev \
    # libpng-dev \
    make

RUN sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'

# Fix typo: apt-key instead of apt-key
RUN apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654

RUN apt-get install -y wget python3-catkin-tool python3-rosinstall python3-rosinstall-generator python3-wstool


RUN apt-get -y install ros-noetic-desktop-full python3-rosdep
## Initialize rosdep
RUN rosdep init
RUN rosdep update

# SOURCE ROS THINGS
RUN echo "source /opt/ros/noetic/setup.bash" >> ~/.bashrc \
    && source ~/.bashrc
