version: '3.9'

services:
  ros1-noetic:
    image: ros-noetic-image
    container_name: ros-noetic-container-test
    build:
      context: .
      dockerfile: Dockerfile.test
    stdin_open: true
    tty: true
    volumes:
      - "/etc/group:/etc/group:rw"
      - "/etc/passwd:/etc/passwd:rw"
      - "/etc/shadow:/etc/shadow:rw"
      - "/etc/sudoers.d:/etc/sudoers.d:rw"
      - "/home:/home"
      - "~/Volumes:/home/usr:rw"
    environment:
      - DISPLAY=:0
      - LIBGL_ALWAYS_SOFTWARE=1
    network_mode: "host"
    user: "${USER}:${USER}"

